export const PUZZLES = [
  {
    id: 'custom_puzzle_1',
    title: 'Princesa Mágica',
    category: 'Princesas',
    emoji: '👸',
    src: '/puzzle_custom_1.jpg',
    description: 'Hermosa princesa mágica en su reino brillante.',
    color: '#EC4899',
  },
  {
    id: 'custom_puzzle_2',
    title: 'Unicornio Fantasía',
    category: 'Unicornios',
    emoji: '🦄',
    src: '/puzzle_custom_2.jpg',
    description: 'Unicornio lleno de magia y colores del arcoíris.',
    color: '#8B5CF6',
  },
  {
    id: 'custom_puzzle_3',
    title: 'Princesa Real',
    category: 'Princesas',
    emoji: '👑',
    src: '/puzzle_custom_3.jpg',
    description: 'Elegante princesa con vestido encantado.',
    color: '#06B6D4',
  },
  {
    id: 'custom_puzzle_4',
    title: 'Unicornio Dulce',
    category: 'Unicornios',
    emoji: '💖',
    src: '/puzzle_custom_4.jpg',
    description: 'Unicornio tierno en un mundo de estrellas.',
    color: '#F43F5E',
  },
  {
    id: 'custom_puzzle_5',
    title: 'Princesa y Unicornio',
    category: 'Ambos',
    emoji: '✨',
    src: '/puzzle_custom_5.jpg',
    description: 'La princesa volando junto a su fiel unicornio.',
    color: '#10B981',
  },
  {
    id: 'custom_puzzle_6',
    title: 'Jardín Encantado',
    category: 'Princesas',
    emoji: '🌸',
    src: '/puzzle_custom_6.jpg',
    description: 'Princesa en un bellísimo jardín lleno de flores.',
    color: '#F59E0B',
  },
  {
    id: 'unicornio_arcoiris',
    title: 'Unicornio Mágico',
    category: 'Unicornios',
    emoji: '🦄',
    src: '/puzzle_unicorn.png',
    description: 'Unicornio en un bosque encantado lleno de estrellas y arcoíris.',
    color: '#EC4899',
  },
  {
    id: 'princesa_castillo',
    title: 'Princesa del Castillo',
    category: 'Princesas',
    emoji: '👸',
    src: '/puzzle_princess.png',
    description: 'Princesa mágica frente a su hermoso palacio.',
    color: '#8B5CF6',
  },
  {
    id: 'princesa_unicornio',
    title: 'Princesa y su Unicornio',
    category: 'Ambos',
    emoji: '✨',
    src: '/puzzle_princess_unicorn.png',
    description: 'Princesa volando junto a su unicornio bajo las estrellas.',
    color: '#06B6D4',
  },
];
