// Comprehensive dataset of simple Spanish words grouped by consonant (Omitting 'H')
// 20 consonants x 25 words = 500 exercises total

export const ALL_CONSONANTS = ['B', 'C', 'D', 'F', 'G', 'J', 'K', 'L', 'M', 'N', 'Ñ', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z'];

export const WORDS_BY_CONSONANT = {
  B: [
    { word: 'BATE', syllables: ['BA', 'TE'], emoji: '🏏' },
    { word: 'BOTA', syllables: ['BO', 'TA'], emoji: '🥾' },
    { word: 'BOLA', syllables: ['BO', 'LA'], emoji: '⚽' },
    { word: 'BESO', syllables: ['BE', 'SO'], emoji: '💋' },
    { word: 'BICI', syllables: ['BI', 'CI'], emoji: '🚲' },
    { word: 'BÚHO', syllables: ['BÚ', 'HO'], emoji: '🦉' },
    { word: 'BARCO', syllables: ['BAR', 'CO'], emoji: '⛵' },
    { word: 'BOTÓN', syllables: ['BO', 'TÓN'], emoji: '🔘' },
    { word: 'BEBÉ', syllables: ['BE', 'BÉ'], emoji: '👶' },
    { word: 'BOTE', syllables: ['BO', 'TE'], emoji: '🚤' },
    { word: 'BURRO', syllables: ['BU', 'RRO'], emoji: '🫏' },
    { word: 'BOCA', syllables: ['BO', 'CA'], emoji: '👄' },
    { word: 'BASE', syllables: ['BA', 'SE'], emoji: '⚾' },
    { word: 'BAÑO', syllables: ['BA', 'ÑO'], emoji: '🛁' },
    { word: 'BALÓN', syllables: ['BA', 'LÓN'], emoji: '🏀' },
    { word: 'BALA', syllables: ['BA', 'LA'], emoji: '🎯' },
    { word: 'BATA', syllables: ['BA', 'TA'], emoji: '🥼' },
    { word: 'BOSQUE', syllables: ['BOS', 'QUE'], emoji: '🌲' },
    { word: 'BURGER', syllables: ['BUR', 'GER'], emoji: '🍔' },
    { word: 'BOLSA', syllables: ['BOL', 'SA'], emoji: '👜' },
    { word: 'BANANA', syllables: ['BA', 'NA', 'NA'], emoji: '🍌' },
    { word: 'BALCÓN', syllables: ['BAL', 'CÓN'], emoji: '🏙️' },
    { word: 'BILLETE', syllables: ['BIL', 'LE', 'TE'], emoji: '💵' },
    { word: 'BOMBERO', syllables: ['BOM', 'BE', 'RO'], emoji: '👨‍🚒' },
    { word: 'BOTELLA', syllables: ['BO', 'TEL', 'LA'], emoji: '🍾' }
  ],
  C: [
    { word: 'CASA', syllables: ['CA', 'SA'], emoji: '🏠' },
    { word: 'COPA', syllables: ['CO', 'PA'], emoji: '🏆' },
    { word: 'CAMA', syllables: ['CA', 'MA'], emoji: '🛏️' },
    { word: 'CUNA', syllables: ['CU', 'NA'], emoji: '👶' },
    { word: 'COCO', syllables: ['CO', 'CO'], emoji: '🥥' },
    { word: 'CERO', syllables: ['CE', 'RO'], emoji: '0️⃣' },
    { word: 'CINE', syllables: ['CI', 'NE'], emoji: '🍿' },
    { word: 'CONEJO', syllables: ['CO', 'NE', 'JO'], emoji: '🐰' },
    { word: 'CARA', syllables: ['CA', 'RA'], emoji: '😊' },
    { word: 'CAJA', syllables: ['CA', 'JA'], emoji: '📦' },
    { word: 'COLA', syllables: ['CO', 'LA'], emoji: '🥤' },
    { word: 'COCHE', syllables: ['CO', 'CHE'], emoji: '🚗' },
    { word: 'CARTA', syllables: ['CAR', 'TA'], emoji: '✉️' },
    { word: 'CERDO', syllables: ['CER', 'DO'], emoji: '🐷' },
    { word: 'CINTA', syllables: ['CIN', 'TA'], emoji: '🎗️' },
    { word: 'COMIDA', syllables: ['CO', 'MI', 'DA'], emoji: '🍲' },
    { word: 'CAMINO', syllables: ['CA', 'MI', 'NO'], emoji: '🛣️' },
    { word: 'CABALLO', syllables: ['CA', 'BAL', 'LO'], emoji: '🐴' },
    { word: 'CORONA', syllables: ['CO', 'RO', 'NA'], emoji: '👑' },
    { word: 'COCINA', syllables: ['CO', 'CI', 'NA'], emoji: '🍳' },
    { word: 'CORAZÓN', syllables: ['CO', 'RA', 'ZÓN'], emoji: '❤️' },
    { word: 'CARAMELO', syllables: ['CA', 'RA', 'ME', 'LO'], emoji: '🍬' },
    { word: 'CARRO', syllables: ['CA', 'RRO'], emoji: '🏎️' },
    { word: 'CEPILLO', syllables: ['CE', 'PIL', 'LO'], emoji: '🪥' },
    { word: 'CAMPANA', syllables: ['CAM', 'PA', 'NA'], emoji: '🔔' }
  ],
  D: [
    { word: 'DADO', syllables: ['DA', 'DO'], emoji: '🎲' },
    { word: 'DEDO', syllables: ['DE', 'DO'], emoji: '☝️' },
    { word: 'DONA', syllables: ['DO', 'NA'], emoji: '🍩' },
    { word: 'DIENTE', syllables: ['DIEN', 'TE'], emoji: '🦷' },
    { word: 'DULCE', syllables: ['DUL', 'CE'], emoji: '🍭' },
    { word: 'DAMA', syllables: ['DA', 'MA'], emoji: '💃' },
    { word: 'DELFÍN', syllables: ['DEL', 'FÍN'], emoji: '🐬' },
    { word: 'DISCO', syllables: ['DIS', 'CO'], emoji: '💿' },
    { word: 'DUENDE', syllables: ['DUEN', 'DE'], emoji: '🧝' },
    { word: 'DÍA', syllables: ['DÍ', 'A'], emoji: '☀️' },
    { word: 'DATO', syllables: ['DA', 'TO'], emoji: '📊' },
    { word: 'DOS', syllables: ['DOS'], emoji: '2️⃣' },
    { word: 'DOCE', syllables: ['DO', 'CE'], emoji: '1️⃣2️⃣' },
    { word: 'DINERO', syllables: ['DI', 'NE', 'RO'], emoji: '💰' },
    { word: 'DUCHA', syllables: ['DU', 'CHA'], emoji: '🚿' },
    { word: 'DURA', syllables: ['DU', 'RA'], emoji: '🪨' },
    { word: 'DÁTIL', syllables: ['DÁ', 'TIL'], emoji: '🌴' },
    { word: 'DORADO', syllables: ['DO', 'RA', 'DO'], emoji: '🥇' },
    { word: 'DOCTOR', syllables: ['DOC', 'TOR'], emoji: '👨‍⚕️' },
    { word: 'DORMIR', syllables: ['DOR', 'MIR'], emoji: '😴' },
    { word: 'DIBUJO', syllables: ['DI', 'BU', 'JO'], emoji: '🎨' },
    { word: 'DEDAL', syllables: ['DE', 'DAL'], emoji: '🧵' },
    { word: 'DELANTAL', syllables: ['DE', 'LAN', 'TAL'], emoji: '🩲' },
    { word: 'DURAZNO', syllables: ['DU', 'RAZ', 'NO'], emoji: '🍑' },
    { word: 'DIAMANTE', syllables: ['DIA', 'MAN', 'TE'], emoji: '💎' }
  ],
  F: [
    { word: 'FOCA', syllables: ['FO', 'CA'], emoji: '🦭' },
    { word: 'FUEGO', syllables: ['FUE', 'GO'], emoji: '🔥' },
    { word: 'FLOR', syllables: ['FLOR'], emoji: '🌸' },
    { word: 'FOTO', syllables: ['FO', 'TO'], emoji: '📷' },
    { word: 'FIESTA', syllables: ['FIES', 'TA'], emoji: '🎉' },
    { word: 'FARO', syllables: ['FA', 'RO'], emoji: '🚨' },
    { word: 'FINO', syllables: ['FI', 'NO'], emoji: '✨' },
    { word: 'FAROL', syllables: ['FA', 'ROL'], emoji: '🏮' },
    { word: 'FLAMENCO', syllables: ['FLA', 'MEN', 'CO'], emoji: '🦩' },
    { word: 'FIDEOS', syllables: ['FI', 'DE', 'OS'], emoji: '🍜' },
    { word: 'FIGURA', syllables: ['FI', 'GU', 'RA'], emoji: '🔺' },
    { word: 'FICHA', syllables: ['FI', 'CHA'], emoji: '🧩' },
    { word: 'FALDA', syllables: ['FAL', 'DA'], emoji: '👗' },
    { word: 'FERIA', syllables: ['FE', 'RIA'], emoji: '🎡' },
    { word: 'FORMA', syllables: ['FOR', 'MA'], emoji: '🟩' },
    { word: 'FRESA', syllables: ['FRE', 'SA'], emoji: '🍓' },
    { word: 'FRENTE', syllables: ['FREN', 'TE'], emoji: '👦' },
    { word: 'FÚTBOL', syllables: ['FÚT', 'BOL'], emoji: '⚽' },
    { word: 'FUENTE', syllables: ['FUEN', 'TE'], emoji: '⛲' },
    { word: 'FAMILIA', syllables: ['FA', 'MI', 'LIA'], emoji: '👨‍👩‍👧' },
    { word: 'FANTASMA', syllables: ['FAN', 'TAS', 'MA'], emoji: '👻' },
    { word: 'FÁBRICA', syllables: ['FÁ', 'BRI', 'CA'], emoji: '🏭' },
    { word: 'FÓSFORO', syllables: ['FÓS', 'FO', 'RO'], emoji: '🕯️' },
    { word: 'FARMACIA', syllables: ['FAR', 'MA', 'CIA'], emoji: '💊' },
    { word: 'FLAUTA', syllables: ['FLAU', 'TA'], emoji: '🪈' }
  ],
  G: [
    { word: 'GATO', syllables: ['GA', 'TO'], emoji: '🐱' },
    { word: 'GOMA', syllables: ['GO', 'MA'], emoji: '🛞' },
    { word: 'GOTA', syllables: ['GO', 'TA'], emoji: '💧' },
    { word: 'GORRA', syllables: ['GO', 'RRA'], emoji: '🧢' },
    { word: 'GALLO', syllables: ['GAL', 'LO'], emoji: '🐓' },
    { word: 'GUSANO', syllables: ['GU', 'SA', 'NO'], emoji: '🐛' },
    { word: 'GALLETA', syllables: ['GAL', 'LE', 'TA'], emoji: '🍪' },
    { word: 'GOL', syllables: ['GOL'], emoji: '⚽' },
    { word: 'GUITARRA', syllables: ['GUI', 'TAR', 'RA'], emoji: '🎸' },
    { word: 'GIGANTE', syllables: ['GI', 'GAN', 'TE'], emoji: '👹' },
    { word: 'GEMELO', syllables: ['GE', 'ME', 'LO'], emoji: '👯' },
    { word: 'GARRAS', syllables: ['GAR', 'RAS'], emoji: '🐾' },
    { word: 'GUANTE', syllables: ['GUAN', 'TE'], emoji: '🥊' },
    { word: 'GORILA', syllables: ['GO', 'RI', 'LA'], emoji: '🦍' },
    { word: 'GAFAS', syllables: ['GA', 'FAS'], emoji: '👓' },
    { word: 'GUISANTE', syllables: ['GUI', 'SAN', 'TE'], emoji: '🫛' },
    { word: 'GLOBO', syllables: ['GLO', 'BO'], emoji: '🎈' },
    { word: 'GIRASOL', syllables: ['GI', 'RA', 'SOL'], emoji: '🌻' },
    { word: 'GARAJE', syllables: ['GA', 'RA', 'JE'], emoji: '🏠' },
    { word: 'GANCHO', syllables: ['GAN', 'CHO'], emoji: '🪝' },
    { word: 'GIMNASIO', syllables: ['GIM', 'NA', 'SIO'], emoji: '🏋️' },
    { word: 'GAVIOTA', syllables: ['GA', 'VIO', 'TA'], emoji: '🐦' },
    { word: 'GATITO', syllables: ['GA', 'TI', 'TO'], emoji: '🐾' },
    { word: 'GOTA', syllables: ['GO', 'TA'], emoji: '🌧️' },
    { word: 'GUITARRA', syllables: ['GUI', 'TA', 'RRA'], emoji: '🎵' }
  ],
  J: [
    { word: 'JIRAFA', syllables: ['JI', 'RA', 'FA'], emoji: '🦒' },
    { word: 'JABÓN', syllables: ['JA', 'BÓN'], emoji: '🧼' },
    { word: 'JUGO', syllables: ['JU', 'GO'], emoji: '🧃' },
    { word: 'JARRA', syllables: ['JAR', 'RA'], emoji: '🏺' },
    { word: 'JUGUETE', syllables: ['JU', 'GUE', 'TE'], emoji: '🧸' },
    { word: 'JOYAS', syllables: ['JO', 'YAS'], emoji: '💎' },
    { word: 'JAMÓN', syllables: ['JA', 'MÓN'], emoji: '🍖' },
    { word: 'JARDÍN', syllables: ['JAR', 'DÍN'], emoji: '🏡' },
    { word: 'JAULA', syllables: ['JAU', 'LA'], emoji: '🧺' },
    { word: 'JUNIO', syllables: ['JU', 'NIO'], emoji: '📅' },
    { word: 'JULIO', syllables: ['JU', 'LIO'], emoji: '🗓️' },
    { word: 'JUEGO', syllables: ['JUE', 'GO'], emoji: '🎮' },
    { word: 'JOVEN', syllables: ['JO', 'VEN'], emoji: '👦' },
    { word: 'JUEZ', syllables: ['JUEZ'], emoji: '👨‍⚖️' },
    { word: 'JAPÓN', syllables: ['JA', 'PÓN'], emoji: '🗾' },
    { word: 'JUNTOS', syllables: ['JUN', 'TOS'], emoji: '🤝' },
    { word: 'JAGUAR', syllables: ['JA', 'GUAR'], emoji: '🐆' },
    { word: 'JÍCAMA', syllables: ['JÍ', 'CA', 'MA'], emoji: '🥗' },
    { word: 'JERINGA', syllables: ['JE', 'RIN', 'GA'], emoji: '💉' },
    { word: 'JINETE', syllables: ['JI', 'NE', 'TE'], emoji: '🏇' },
    { word: 'JUEVES', syllables: ['JUE', 'VES'], emoji: '📆' },
    { word: 'JOYERÍA', syllables: ['JO', 'YE', 'RÍA'], emoji: '💍' },
    { word: 'JABALÍ', syllables: ['JA', 'BA', 'LÍ'], emoji: '🐗' },
    { word: 'JAZMÍN', syllables: ['JAZ', 'MÍN'], emoji: '🌼' },
    { word: 'JUGADOR', syllables: ['JU', 'GA', 'DOR'], emoji: '🏃' }
  ],
  K: [
    { word: 'KOALA', syllables: ['KO', 'A', 'LA'], emoji: '🐨' },
    { word: 'KIWI', syllables: ['KI', 'WI'], emoji: '🥝' },
    { word: 'KILO', syllables: ['KI', 'LO'], emoji: '⚖️' },
    { word: 'KARATE', syllables: ['KA', 'RA', 'TE'], emoji: '🥋' },
    { word: 'KETCHUP', syllables: ['KET', 'CHUP'], emoji: '🥫' },
    { word: 'KIMONO', syllables: ['KI', 'MO', 'NO'], emoji: '👘' },
    { word: 'KANOA', syllables: ['KA', 'NO', 'A'], emoji: '🛶' },
    { word: 'KART', syllables: ['KART'], emoji: '🏎️' },
    { word: 'KEVIN', syllables: ['KE', 'VIN'], emoji: '👦' },
    { word: 'KAYAK', syllables: ['KA', 'YAK'], emoji: '🚣' },
    { word: 'KENDO', syllables: ['KEN', 'DO'], emoji: '⚔️' },
    { word: 'KEFIR', syllables: ['KE', 'FIR'], emoji: '🥛' },
    { word: 'KAPPA', syllables: ['KAP', 'PA'], emoji: '🐸' },
    { word: 'KILÓMETRO', syllables: ['KI', 'LÓ', 'ME', 'TRO'], emoji: '📏' },
    { word: 'KARATEKA', syllables: ['KA', 'RA', 'TE', 'KA'], emoji: '🥷' },
    { word: 'KIOSKO', syllables: ['KIOS', 'KO'], emoji: '🏪' },
    { word: 'KILOGRAMO', syllables: ['KI', 'LO', 'GRA', 'MO'], emoji: '📦' },
    { word: 'KING', syllables: ['KING'], emoji: '👑' },
    { word: 'KILOVATIO', syllables: ['KI', 'LO', 'VA', 'TIO'], emoji: '⚡' },
    { word: 'KARATE', syllables: ['KA', 'RA', 'TE'], emoji: '🏅' },
    { word: 'KETCHUP', syllables: ['KET', 'CHUP'], emoji: '🍟' },
    { word: 'KOALAS', syllables: ['KO', 'A', 'LAS'], emoji: '🐨' },
    { word: 'KIWIS', syllables: ['KI', 'WIS'], emoji: '🥝' },
    { word: 'KAREN', syllables: ['KA', 'REN'], emoji: '👧' },
    { word: 'KARATE', syllables: ['KA', 'RA', 'TE'], emoji: '🥋' }
  ],
  L: [
    { word: 'LUNA', syllables: ['LU', 'NA'], emoji: '🌙' },
    { word: 'LÁPIZ', syllables: ['LÁ', 'PIZ'], emoji: '✏️' },
    { word: 'LIMA', syllables: ['LI', 'MA'], emoji: '🍋' },
    { word: 'LOBO', syllables: ['LO', 'BO'], emoji: '🐺' },
    { word: 'LATA', syllables: ['LA', 'TA'], emoji: '🥫' },
    { word: 'LAGO', syllables: ['LA', 'GO'], emoji: '🏞️' },
    { word: 'LORO', syllables: ['LO', 'RO'], emoji: '🦜' },
    { word: 'LECHE', syllables: ['LE', 'CHE'], emoji: '🥛' },
    { word: 'LIMÓN', syllables: ['LI', 'MÓN'], emoji: '🍋' },
    { word: 'LEÓN', syllables: ['LE', 'ÓN'], emoji: '🦁' },
    { word: 'LUZ', syllables: ['LUZ'], emoji: '💡' },
    { word: 'LIBRO', syllables: ['LI', 'BRO'], emoji: '📚' },
    { word: 'LUPA', syllables: ['LU', 'PA'], emoji: '🔍' },
    { word: 'LLAVE', syllables: ['LLA', 'VE'], emoji: '🔑' },
    { word: 'LLAMA', syllables: ['LLA', 'MA'], emoji: '🦙' },
    { word: 'LLUVIA', syllables: ['LLU', 'VIA'], emoji: '🌧️' },
    { word: 'LUNARES', syllables: ['LU', 'NA', 'RES'], emoji: '🔴' },
    { word: 'LECHUZA', syllables: ['LE', 'CHU', 'ZA'], emoji: '🦉' },
    { word: 'LÁMPARA', syllables: ['LÁM', 'PA', 'RA'], emoji: '🛋️' },
    { word: 'LADRILLO', syllables: ['LA', 'DRI', 'LLO'], emoji: '🧱' },
    { word: 'LANCHA', syllables: ['LAN', 'CHA'], emoji: '🚤' },
    { word: 'LECTURA', syllables: ['LEC', 'TU', 'RA'], emoji: '📖' },
    { word: 'LIBERTAD', syllables: ['LI', 'BER', 'TAD'], emoji: '🕊️' },
    { word: 'LUGAR', syllables: ['LU', 'GAR'], emoji: '📍' },
    { word: 'LUMBRERA', syllables: ['LUM', 'BRE', 'RA'], emoji: '✨' }
  ],
  M: [
    { word: 'MAMÁ', syllables: ['MA', 'MÁ'], emoji: '👩' },
    { word: 'MESA', syllables: ['ME', 'SA'], emoji: '🍽️' },
    { word: 'MONO', syllables: ['MO', 'NO'], emoji: '🐒' },
    { word: 'MULA', syllables: ['MU', 'LA'], emoji: '🫏' },
    { word: 'MISA', syllables: ['MI', 'SA'], emoji: '⛪' },
    { word: 'MAPA', syllables: ['MA', 'PA'], emoji: '🗺️' },
    { word: 'MASA', syllables: ['MA', 'SA'], emoji: '🥖' },
    { word: 'MOTO', syllables: ['MO', 'TO'], emoji: '🏍️' },
    { word: 'MORA', syllables: ['MO', 'RA'], emoji: '🫐' },
    { word: 'MIEL', syllables: ['MIEL'], emoji: '🍯' },
    { word: 'MANZANA', syllables: ['MAN', 'ZA', 'NA'], emoji: '🍎' },
    { word: 'MONEDA', syllables: ['MO', 'NE', 'DA'], emoji: '🪙' },
    { word: 'MARIPOSA', syllables: ['MA', 'RI', 'PO', 'SA'], emoji: '🦋' },
    { word: 'MANO', syllables: ['MA', 'NO'], emoji: '✋' },
    { word: 'MADRE', syllables: ['MA', 'DRE'], emoji: '👩‍👧' },
    { word: 'MAR', syllables: ['MAR'], emoji: '🌊' },
    { word: 'MÚSICA', syllables: ['MÚ', 'SI', 'CA'], emoji: '🎵' },
    { word: 'MEDALLA', syllables: ['ME', 'DAL', 'LA'], emoji: '🏅' },
    { word: 'MUÑECA', syllables: ['MU', 'ÑE', 'CA'], emoji: '🪆' },
    { word: 'MANGO', syllables: ['MAN', 'GO'], emoji: '🥭' },
    { word: 'MONTAÑA', syllables: ['MON', 'TA', 'ÑA'], emoji: '🏔️' },
    { word: 'MOLINO', syllables: ['MO', 'LI', 'NO'], emoji: '🌪️' },
    { word: 'MOCHILA', syllables: ['MO', 'CHI', 'LA'], emoji: '🎒' },
    { word: 'MAÍZ', syllables: ['MA', 'ÍZ'], emoji: '🌽' },
    { word: 'MACETA', syllables: ['MA', 'CE', 'TA'], emoji: '🪴' }
  ],
  N: [
    { word: 'NIDO', syllables: ['NI', 'DO'], emoji: '🪹' },
    { word: 'NUBE', syllables: ['NU', 'BE'], emoji: '☁️' },
    { word: 'NAVE', syllables: ['NA', 'VE'], emoji: '🚀' },
    { word: 'NIÑO', syllables: ['NI', 'ÑO'], emoji: '👦' },
    { word: 'NOTA', syllables: ['NO', 'TA'], emoji: '🎵' },
    { word: 'NUEZ', syllables: ['NUEZ'], emoji: '🥜' },
    { word: 'NIÑA', syllables: ['NI', 'ÑA'], emoji: '👧' },
    { word: 'NAVIDAD', syllables: ['NA', 'VI', 'DAD'], emoji: '🎄' },
    { word: 'NARIZ', syllables: ['NA', 'RIZ'], emoji: '👃' },
    { word: 'NOCHE', syllables: ['NO', 'CHE'], emoji: '🌌' },
    { word: 'NIEVE', syllables: ['NIE', 'VE'], emoji: '❄️' },
    { word: 'NARANJA', syllables: ['NA', 'RAN', 'JA'], emoji: '🍊' },
    { word: 'NADAR', syllables: ['NA', 'DAR'], emoji: '🏊' },
    { word: 'NÚMERO', syllables: ['NÚ', 'ME', 'RO'], emoji: '🔢' },
    { word: 'NEGRO', syllables: ['NE', 'GRO'], emoji: '⬛' },
    { word: 'NÉCTAR', syllables: ['NÉC', 'TAR'], emoji: '🧃' },
    { word: 'NOPAL', syllables: ['NO', 'PAL'], emoji: '🌵' },
    { word: 'NOVIEMBRE', syllables: ['NO', 'VIEM', 'BRE'], emoji: '📅' },
    { word: 'NAVEGANTE', syllables: ['NA', 'VE', 'GAN', 'TE'], emoji: '⛵' },
    { word: 'NIDO', syllables: ['NI', 'DO'], emoji: '🪺' },
    { word: 'NUBE', syllables: ['NU', 'BE'], emoji: '🌧️' },
    { word: 'NUEVE', syllables: ['NUE', 'VE'], emoji: '9️⃣' },
    { word: 'NAVIO', syllables: ['NA', 'VIO'], emoji: '🚢' },
    { word: 'NÁUTICO', syllables: ['NÁU', 'TI', 'CO'], emoji: '⚓' },
    { word: 'NICK', syllables: ['NICK'], emoji: '👦' }
  ],
  Ñ: [
    { word: 'ÑANDÚ', syllables: ['ÑA', 'NDÚ'], emoji: '🦤' },
    { word: 'ÑAME', syllables: ['ÑA', 'ME'], emoji: '🍠' },
    { word: 'ÑU', syllables: ['ÑU'], emoji: '🐂' },
    { word: 'MOÑO', syllables: ['MO', 'ÑO'], emoji: '🎀' },
    { word: 'PIÑA', syllables: ['PI', 'ÑA'], emoji: '🍍' },
    { word: 'NIÑA', syllables: ['NI', 'ÑA'], emoji: '👧' },
    { word: 'NIÑO', syllables: ['NI', 'ÑO'], emoji: '👦' },
    { word: 'CAÑA', syllables: ['CA', 'ÑA'], emoji: '🎋' },
    { word: 'LEÑA', syllables: ['LE', 'ÑA'], emoji: '🪵' },
    { word: 'PUÑO', syllables: ['PU', 'ÑO'], emoji: '👊' },
    { word: 'SEÑA', syllables: ['SE', 'ÑA'], emoji: '👉' },
    { word: 'UÑA', syllables: ['U', 'ÑA'], emoji: '💅' },
    { word: 'PAÑUELO', syllables: ['PA', 'ÑUE', 'LO'], emoji: '🤧' },
    { word: 'MAÑANA', syllables: ['MA', 'ÑA', 'NA'], emoji: '🌅' },
    { word: 'ARAÑA', syllables: ['A', 'RA', 'ÑA'], emoji: '🕷️' },
    { word: 'MONTAÑA', syllables: ['MON', 'TA', 'ÑA'], emoji: '⛰️' },
    { word: 'CABAÑA', syllables: ['CA', 'BA', 'ÑA'], emoji: '🏡' },
    { word: 'CAÑÓN', syllables: ['CA', 'ÑÓN'], emoji: '🏞️' },
    { word: 'BAÑO', syllables: ['BA', 'ÑO'], emoji: '🛁' },
    { word: 'SUEÑO', syllables: ['SUE', 'ÑO'], emoji: '😴' },
    { word: 'OTOÑO', syllables: ['O', 'TO', 'ÑO'], emoji: '🍂' },
    { word: 'SEÑOR', syllables: ['SE', 'ÑOR'], emoji: '👨' },
    { word: 'PEQUEÑO', syllables: ['PE', 'QUE', 'ÑO'], emoji: '🐥' },
    { word: 'AÑO', syllables: ['A', 'ÑO'], emoji: '🎆' },
    { word: 'CAÑADA', syllables: ['CA', 'ÑA', 'DA'], emoji: '🏞️' }
  ],
  P: [
    { word: 'PAPÁ', syllables: ['PA', 'PÁ'], emoji: '👨' },
    { word: 'PATO', syllables: ['PA', 'TO'], emoji: '🦆' },
    { word: 'PELOTA', syllables: ['PE', 'LO', 'TA'], emoji: '⚽' },
    { word: 'PERRO', syllables: ['PE', 'RRO'], emoji: '🐶' },
    { word: 'PEZ', syllables: ['PEZ'], emoji: '🐟' },
    { word: 'PIPA', syllables: ['PI', 'PA'], emoji: '🪈' },
    { word: 'PIANO', syllables: ['PIA', 'NO'], emoji: '🎹' },
    { word: 'PIÑA', syllables: ['PI', 'ÑA'], emoji: '🍍' },
    { word: 'POLO', syllables: ['PO', 'LO'], emoji: '🍧' },
    { word: 'PUERTA', syllables: ['PUER', 'TA'], emoji: '🚪' },
    { word: 'PAN', syllables: ['PAN'], emoji: '🍞' },
    { word: 'POLLITO', syllables: ['POL', 'LI', 'TO'], emoji: '🐥' },
    { word: 'PARQUE', syllables: ['PAR', 'QUE'], emoji: '🛝' },
    { word: 'PÁJARO', syllables: ['PÁ', 'JA', 'RO'], emoji: '🐦' },
    { word: 'PALOMA', syllables: ['PA', 'LO', 'MA'], emoji: '🕊️' },
    { word: 'PAYASO', syllables: ['PA', 'YA', 'SO'], emoji: '🤡' },
    { word: 'PELO', syllables: ['PE', 'LO'], emoji: '💇' },
    { word: 'PINCEL', syllables: ['PIN', 'CEL'], emoji: '🖌️' },
    { word: 'PLANETA', syllables: ['PLA', 'NE', 'TA'], emoji: '🪐' },
    { word: 'PUENTE', syllables: ['PUEN', 'TE'], emoji: '🌉' },
    { word: 'PULPO', syllables: ['PUL', 'PO'], emoji: '🐙' },
    { word: 'PASTEL', syllables: ['PAS', 'TEL'], emoji: '🎂' },
    { word: 'PIRATA', syllables: ['PI', 'RA', 'TA'], emoji: '🏴‍☠️' },
    { word: 'PELUCHE', syllables: ['PE', 'LU', 'CHE'], emoji: '🧸' },
    { word: 'PALETA', syllables: ['PA', 'LE', 'TA'], emoji: '🍭' }
  ],
  Q: [
    { word: 'QUESO', syllables: ['QUE', 'SO'], emoji: '🧀' },
    { word: 'QUEMAR', syllables: ['QUE', 'MAR'], emoji: '🔥' },
    { word: 'QUINCE', syllables: ['QUIN', 'CE'], emoji: '1️⃣5️⃣' },
    { word: 'QUÍMICA', syllables: ['QUÍ', 'MI', 'CA'], emoji: '🧪' },
    { word: 'QUERER', syllables: ['QUE', 'RER'], emoji: '❤️' },
    { word: 'QUIMONO', syllables: ['QUI', 'MO', 'NO'], emoji: '👘' },
    { word: 'QUETZAL', syllables: ['QUET', 'ZAL'], emoji: '🦜' },
    { word: 'QUINOA', syllables: ['QUI', 'NOA'], emoji: '🌾' },
    { word: 'QUERUBÍN', syllables: ['QUE', 'RU', 'BÍN'], emoji: '👼' },
    { word: 'QUEBRADA', syllables: ['QUE', 'BRA', 'DA'], emoji: '🏞️' },
    { word: 'QUEJIDO', syllables: ['QUE', 'JI', 'DO'], emoji: '🗣️' },
    { word: 'QUEMADO', syllables: ['QUE', 'MA', 'DO'], emoji: '🍳' },
    { word: 'QUERIDO', syllables: ['QUE', 'RI', 'DO'], emoji: '🤗' },
    { word: 'QUICHUA', syllables: ['QUI', 'CHUA'], emoji: '🏞️' },
    { word: 'QUINIENTOS', syllables: ['QUI', 'NIEN', 'TOS'], emoji: '5️⃣0️⃣0️⃣' },
    { word: 'QUINTA', syllables: ['QUIN', 'TA'], emoji: '🏡' },
    { word: 'QUESADILLA', syllables: ['QUE', 'SA', 'DIL', 'LA'], emoji: '🌮' },
    { word: 'QUESERA', syllables: ['QUE', 'SE', 'RA'], emoji: '🧀' },
    { word: 'QUETZALES', syllables: ['QUET', 'ZA', 'LES'], emoji: '🪶' },
    { word: 'QUINCENA', syllables: ['QUIN', 'CE', 'NA'], emoji: '📅' },
    { word: 'QUINETO', syllables: ['QUI', 'NE', 'TO'], emoji: '🧪' },
    { word: 'QUINTAL', syllables: ['QUIN', 'TAL'], emoji: '📦' },
    { word: 'QUIMERA', syllables: ['QUI', 'ME', 'RA'], emoji: '🦄' },
    { word: 'QUITO', syllables: ['QUI', 'TO'], emoji: '🇪🇨' },
    { word: 'QUERATINA', syllables: ['QUE', 'RA', 'TI', 'NA'], emoji: '💅' }
  ],
  R: [
    { word: 'RATÓN', syllables: ['RA', 'TÓN'], emoji: '🐭' },
    { word: 'ROSA', syllables: ['RO', 'SA'], emoji: '🌹' },
    { word: 'RANA', syllables: ['RA', 'NA'], emoji: '🐸' },
    { word: 'RÍO', syllables: ['RÍ', 'O'], emoji: '🏞️' },
    { word: 'ROPA', syllables: ['RO', 'PA'], emoji: '👕' },
    { word: 'RUEDA', syllables: ['RUE', 'DA'], emoji: '🛞' },
    { word: 'REGALO', syllables: ['RE', 'GA', 'LO'], emoji: '🎁' },
    { word: 'RELOJ', syllables: ['RE', 'LOJ'], emoji: '⏰' },
    { word: 'ROBOT', syllables: ['RO', 'BOT'], emoji: '🤖' },
    { word: 'RAMA', syllables: ['RA', 'MA'], emoji: '🌿' },
    { word: 'REY', syllables: ['REY'], emoji: '👑' },
    { word: 'REINA', syllables: ['REI', 'NA'], emoji: '👸' },
    { word: 'RAYO', syllables: ['RA', 'YO'], emoji: '⚡' },
    { word: 'RAQUETA', syllables: ['RA', 'QUE', 'TA'], emoji: '🎾' },
    { word: 'RISA', syllables: ['RI', 'SA'], emoji: '😄' },
    { word: 'ROCA', syllables: ['RO', 'CA'], emoji: '🪨' },
    { word: 'RULETA', syllables: ['RU', 'LE', 'TA'], emoji: '🎯' },
    { word: 'RAMO', syllables: ['RA', 'MO'], emoji: '💐' },
    { word: 'REMO', syllables: ['RE', 'MO'], emoji: '🚣' },
    { word: 'RAÍZ', syllables: ['RA', 'ÍZ'], emoji: '🌱' },
    { word: 'REFRESCO', syllables: ['RE', 'FRES', 'CO'], emoji: '🥤' },
    { word: 'ROBLE', syllables: ['RO', 'BLE'], emoji: '🌳' },
    { word: 'RINOCERONTE', syllables: ['RI', 'NO', 'CE', 'RON', 'TE'], emoji: '🦏' },
    { word: 'ROSETA', syllables: ['RO', 'SE', 'TA'], emoji: '🏵️' },
    { word: 'ROQUETA', syllables: ['RO', 'QUE', 'TA'], emoji: '🚀' }
  ],
  S: [
    { word: 'SAPO', syllables: ['SA', 'PO'], emoji: '🐸' },
    { word: 'SOL', syllables: ['SOL'], emoji: '☀️' },
    { word: 'SOPA', syllables: ['SO', 'PA'], emoji: '🥣' },
    { word: 'SILLA', syllables: ['SIL', 'LA'], emoji: '🪑' },
    { word: 'SUMA', syllables: ['SU', 'MA'], emoji: '➕' },
    { word: 'SIRENA', syllables: ['SI', 'RE', 'NA'], emoji: '🧜‍♀️' },
    { word: 'SERPIENTE', syllables: ['SER', 'PIEN', 'TE'], emoji: '🐍' },
    { word: 'SOMBRERO', syllables: ['SOM', 'BRE', 'RO'], emoji: '🎩' },
    { word: 'SUBIR', syllables: ['SU', 'BIR'], emoji: '🧗' },
    { word: 'SOMBRA', syllables: ['SOM', 'BRA'], emoji: '👤' },
    { word: 'SEMILLA', syllables: ['SE', 'MIL', 'LA'], emoji: '🌱' },
    { word: 'SIETE', syllables: ['SIE', 'TE'], emoji: '7️⃣' },
    { word: 'SARTÉN', syllables: ['SAR', 'TÉN'], emoji: '🍳' },
    { word: 'SOBRE', syllables: ['SO', 'BRE'], emoji: '✉️' },
    { word: 'SILBATO', syllables: ['SIL', 'BA', 'TO'], emoji: '📣' },
    { word: 'SÁBANA', syllables: ['SÁ', 'BA', 'NA'], emoji: '🛏️' },
    { word: 'SELVA', syllables: ['SEL', 'VA'], emoji: '🌴' },
    { word: 'SONRISA', syllables: ['SON', 'RI', 'SA'], emoji: '😊' },
    { word: 'SOPLIDO', syllables: ['SOP', 'LI', 'DO'], emoji: '💨' },
    { word: 'SANDÍA', syllables: ['SAN', 'DÍ', 'A'], emoji: '🍉' },
    { word: 'SUDADOR', syllables: ['SU', 'DA', 'DOR'], emoji: '🧥' },
    { word: 'SOLAZ', syllables: ['SO', 'LAZ'], emoji: '🏖️' },
    { word: 'SEGUNDO', syllables: ['SE', 'GUN', 'DO'], emoji: '⏱️' },
    { word: 'SÁBADO', syllables: ['SÁ', 'BA', 'DO'], emoji: '📅' },
    { word: 'SOLAR', syllables: ['SO', 'LAR'], emoji: '☀️' }
  ],
  T: [
    { word: 'TAZA', syllables: ['TA', 'ZA'], emoji: '☕' },
    { word: 'TREN', syllables: ['TREN'], emoji: '🚆' },
    { word: 'TIGRE', syllables: ['TI', 'GRE'], emoji: '🐯' },
    { word: 'TOMATE', syllables: ['TO', 'MA', 'TE'], emoji: '🍅' },
    { word: 'TORTUGA', syllables: ['TOR', 'TU', 'GA'], emoji: '🐢' },
    { word: 'TAMBOR', syllables: ['TAM', 'BOR'], emoji: '🥁' },
    { word: 'TELÉFONO', syllables: ['TE', 'LÉ', 'FO', 'NO'], emoji: '☎️' },
    { word: 'TIJERAS', syllables: ['TI', 'JE', 'RAS'], emoji: '✂️' },
    { word: 'TORO', syllables: ['TO', 'RO'], emoji: '🐂' },
    { word: 'TAZÓN', syllables: ['TA', 'ZÓN'], emoji: '🥣' },
    { word: 'TÍA', syllables: ['TÍ', 'A'], emoji: '👩' },
    { word: 'TÍO', syllables: ['TÍ', 'O'], emoji: '👨' },
    { word: 'TIERRA', syllables: ['TIE', 'RRA'], emoji: '🌍' },
    { word: 'TORNILLO', syllables: ['TOR', 'NIL', 'LO'], emoji: '🔩' },
    { word: 'TARTA', syllables: ['TAR', 'TA'], emoji: '🍰' },
    { word: 'TAPÓN', syllables: ['TA', 'PÓN'], emoji: '🍾' },
    { word: 'TUBO', syllables: ['TU', 'BO'], emoji: '🧪' },
    { word: 'TORRE', syllables: ['TOR', 'RE'], emoji: '🏰' },
    { word: 'TULIPÁN', syllables: ['TU', 'LI', 'PÁN'], emoji: '🌷' },
    { word: 'TÍTERE', syllables: ['TÍ', 'TE', 'RE'], emoji: '🎭' },
    { word: 'TRUENO', syllables: ['TRUE', 'NO'], emoji: '🌩️' },
    { word: 'TESORO', syllables: ['TE', 'SO', 'RO'], emoji: '💎' },
    { word: 'TRIÁNGULO', syllables: ['TRI', 'ÁN', 'GU', 'LO'], emoji: '🔺' },
    { word: 'TEJADO', syllables: ['TE', 'JA', 'DO'], emoji: '🏠' },
    { word: 'TENEDOR', syllables: ['TE', 'NE', 'DOR'], emoji: '🍴' }
  ],
  V: [
    { word: 'VACA', syllables: ['VA', 'CA'], emoji: '🐮' },
    { word: 'VELA', syllables: ['VE', 'LA'], emoji: '🕯️' },
    { word: 'VIENTO', syllables: ['VIEN', 'TO'], emoji: '🌬️' },
    { word: 'VASO', syllables: ['VA', 'SO'], emoji: '🥛' },
    { word: 'VOLCÁN', syllables: ['VOL', 'CÁN'], emoji: '🌋' },
    { word: 'VESTIDO', syllables: ['VES', 'TI', 'DO'], emoji: '👗' },
    { word: 'VECINO', syllables: ['VE', 'CI', 'NO'], emoji: '🏡' },
    { word: 'VIOLETA', syllables: ['VIO', 'LE', 'TA'], emoji: '💜' },
    { word: 'VERDE', syllables: ['VER', 'DE'], emoji: '🟩' },
    { word: 'VENTANA', syllables: ['VEN', 'TA', 'NA'], emoji: '🪟' },
    { word: 'VIAJE', syllables: ['VIA', 'JE'], emoji: '🧳' },
    { word: 'VUELO', syllables: ['VUE', 'LO'], emoji: '✈️' },
    { word: 'VOCAL', syllables: ['VO', 'CAL'], emoji: '🗣️' },
    { word: 'VAMPIRO', syllables: ['VAM', 'PI', 'RO'], emoji: '🧛' },
    { word: 'VAGÓN', syllables: ['VA', 'GÓN'], emoji: '🚃' },
    { word: 'VALIENTE', syllables: ['VA', 'LIEN', 'TE'], emoji: '🦁' },
    { word: 'VACACIONES', syllables: ['VA', 'CA', 'CIO', 'NES'], emoji: '🏖️' },
    { word: 'VELOCIDAD', syllables: ['VE', 'LO', 'CI', 'DAD'], emoji: '🏎️' },
    { word: 'VELERO', syllables: ['VE', 'LE', 'RO'], emoji: '⛵' },
    { word: 'VERANO', syllables: ['VE', 'RA', 'NO'], emoji: '☀️' },
    { word: 'VERDURA', syllables: ['VER', 'DU', 'RA'], emoji: '🥦' },
    { word: 'VIOLÍN', syllables: ['VIO', 'LÍN'], emoji: '🎻' },
    { word: 'VISITANTE', syllables: ['VI', 'SI', 'TAN', 'TE'], emoji: '🙋' },
    { word: 'VIDA', syllables: ['VI', 'DA'], emoji: '🌱' },
    { word: 'VÍA', syllables: ['VÍ', 'A'], emoji: '🛤️' }
  ],
  W: [
    { word: 'WIFI', syllables: ['WI', 'FI'], emoji: '📶' },
    { word: 'WOK', syllables: ['WOK'], emoji: '🥘' },
    { word: 'WAFFLE', syllables: ['WAF', 'FLE'], emoji: '🧇' },
    { word: 'WEB', syllables: ['WEB'], emoji: '🌐' },
    { word: 'WALKIE', syllables: ['WAL', 'KIE'], emoji: '📻' },
    { word: 'WATT', syllables: ['WATT'], emoji: '⚡' },
    { word: 'WINDSURF', syllables: ['WIND', 'SURF'], emoji: '🏄' },
    { word: 'WIGWAM', syllables: ['WIG', 'WAM'], emoji: '⛺' },
    { word: 'WEBCAM', syllables: ['WEB', 'CAM'], emoji: '📹' },
    { word: 'WIKI', syllables: ['WI', 'KI'], emoji: '📚' },
    { word: 'WATERPOLO', syllables: ['WA', 'TER', 'PO', 'LO'], emoji: '🤽' },
    { word: 'WALKMAN', syllables: ['WALK', 'MAN'], emoji: '🎧' },
    { word: 'WENDY', syllables: ['WEN', 'DY'], emoji: '👧' },
    { word: 'WALTER', syllables: ['WAL', 'TER'], emoji: '👦' },
    { word: 'WILFRIDO', syllables: ['WIL', 'FRI', 'DO'], emoji: '👨' },
    { word: 'WESTERN', syllables: ['WES', 'TERN'], emoji: '🤠' },
    { word: 'WOOD', syllables: ['WOOD'], emoji: '🪵' },
    { word: 'WASHINGTON', syllables: ['WAS', 'HING', 'TON'], emoji: '🏙️' },
    { word: 'WEBSTER', syllables: ['WEB', 'STER'], emoji: '📖' },
    { word: 'WIKIPEDIA', syllables: ['WI', 'KI', 'PE', 'DIA'], emoji: '🧠' },
    { word: 'WAFFLES', syllables: ['WAF', 'FLES'], emoji: '🧇' },
    { word: 'WIFIS', syllables: ['WI', 'FIS'], emoji: '📶' },
    { word: 'WOKS', syllables: ['WOKS'], emoji: '🥘' },
    { word: 'WATTS', syllables: ['WATTS'], emoji: '⚡' },
    { word: 'WINNER', syllables: ['WIN', 'NER'], emoji: '🏆' }
  ],
  X: [
    { word: 'XILÓFONO', syllables: ['XI', 'LÓ', 'FO', 'NO'], emoji: '🎼' },
    { word: 'XENÓN', syllables: ['XE', 'NÓN'], emoji: '💡' },
    { word: 'XEROGRAFÍA', syllables: ['XE', 'RO', 'GRA', 'FÍA'], emoji: '🟨' },
    { word: 'XIMENA', syllables: ['XI', 'ME', 'NA'], emoji: '👧' },
    { word: 'XAVIER', syllables: ['XA', 'VIER'], emoji: '👦' },
    { word: 'XOCHITL', syllables: ['XO', 'CHITL'], emoji: '🌸' },
    { word: 'TAXI', syllables: ['TA', 'XI'], emoji: '🚕' },
    { word: 'TEXTO', syllables: ['TEX', 'TO'], emoji: '📝' },
    { word: 'ÉXITO', syllables: ['ÉX', 'I', 'TO'], emoji: '🌟' },
    { word: 'ÓXIDO', syllables: ['ÓX', 'I', 'DO'], emoji: '🪨' },
    { word: 'EXAMEN', syllables: ['EX', 'A', 'MEN'], emoji: '📄' },
    { word: 'EXCURSIÓN', syllables: ['EX', 'CUR', 'SIÓN'], emoji: '🚌' },
    { word: 'EXACTO', syllables: ['EX', 'AC', 'TO'], emoji: '🎯' },
    { word: 'OXÍGENO', syllables: ['OX', 'Í', 'GE', 'NO'], emoji: '🫁' },
    { word: 'EXTINTO', syllables: ['EX', 'TIN', 'TO'], emoji: '🦕' },
    { word: 'EXTRA', syllables: ['EX', 'TRA'], emoji: '⭐' },
    { word: 'EXPERTO', syllables: ['EX', 'PER', 'TO'], emoji: '🎓' },
    { word: 'EXPERTOS', syllables: ['EX', 'PER', 'TOS'], emoji: '👨‍🎓' },
    { word: 'EXPLORADOR', syllables: ['EX', 'PLO', 'RA', 'DOR'], emoji: '🧭' },
    { word: 'EXPRESIVO', syllables: ['EX', 'PRE', 'SI', 'VO'], emoji: '🎨' },
    { word: 'TEXTURA', syllables: ['TEX', 'TU', 'RA'], emoji: '🧶' },
    { word: 'FÉLIX', syllables: ['FÉ', 'LIX'], emoji: '🐱' },
    { word: 'FÉNIX', syllables: ['FÉ', 'NIX'], emoji: '🦅' },
    { word: 'BOXEO', syllables: ['BOX', 'E', 'O'], emoji: '🥊' },
    { word: 'MÉXICO', syllables: ['MÉ', 'XI', 'CO'], emoji: '🇲🇽' }
  ],
  Y: [
    { word: 'YATE', syllables: ['YA', 'TE'], emoji: '🛥️' },
    { word: 'YEMA', syllables: ['YE', 'MA'], emoji: '🍳' },
    { word: 'YOGUR', syllables: ['YO', 'GUR'], emoji: '🥛' },
    { word: 'YOYO', syllables: ['YO', 'YO'], emoji: '🪀' },
    { word: 'YEGUAS', syllables: ['YE', 'GUAS'], emoji: '🐴' },
    { word: 'YESO', syllables: ['YE', 'SO'], emoji: '🩹' },
    { word: 'YOGA', syllables: ['YO', 'GA'], emoji: '🧘' },
    { word: 'YUCA', syllables: ['YU', 'CA'], emoji: '🥔' },
    { word: 'YEGUA', syllables: ['YE', 'GUA'], emoji: '🐎' },
    { word: 'YERBA', syllables: ['YER', 'BA'], emoji: '🌿' },
    { word: 'YACARÉ', syllables: ['YA', 'CA', 'RÉ'], emoji: '🐊' },
    { word: 'YODO', syllables: ['YO', 'DO'], emoji: '🧪' },
    { word: 'YUNQUE', syllables: ['YUN', 'QUE'], emoji: '🔨' },
    { word: 'YIP', syllables: ['YIP'], emoji: '🚙' },
    { word: 'YOGURT', syllables: ['YO', 'GURT'], emoji: '🍦' },
    { word: 'YUTE', syllables: ['YU', 'TE'], emoji: '🧵' },
    { word: 'YACIMIENTO', syllables: ['YA', 'CI', 'MIEN', 'TO'], emoji: '💎' },
    { word: 'YUQUITA', syllables: ['YU', 'QUI', 'TA'], emoji: '🍟' },
    { word: 'YUMMY', syllables: ['YUM', 'MY'], emoji: '😋' },
    { word: 'YOYOS', syllables: ['YO', 'YOS'], emoji: '🪀' },
    { word: 'YATERO', syllables: ['YA', 'TE', 'RO'], emoji: '⛵' },
    { word: 'YUNQUES', syllables: ['YUN', 'QUES'], emoji: '🛠️' },
    { word: 'YATES', syllables: ['YA', 'TES'], emoji: '🛥️' },
    { word: 'YEMAS', syllables: ['YE', 'MAS'], emoji: '🥚' },
    { word: 'YOGURES', syllables: ['YO', 'GU', 'RES'], emoji: '🧁' }
  ],
  Z: [
    { word: 'ZAPATO', syllables: ['ZA', 'PA', 'TO'], emoji: '👞' },
    { word: 'ZORRO', syllables: ['ZOR', 'RO'], emoji: '🦊' },
    { word: 'ZUMO', syllables: ['ZU', 'MO'], emoji: '🧃' },
    { word: 'ZEBRA', syllables: ['ZE', 'BRA'], emoji: '🦓' },
    { word: 'ZIGZAG', syllables: ['ZIG', 'ZAG'], emoji: '⚡' },
    { word: 'ZONA', syllables: ['ZO', 'NA'], emoji: '📍' },
    { word: 'ZAPATILLA', syllables: ['ZA', 'PA', 'TIL', 'LA'], emoji: '👟' },
    { word: 'ZANAHORIA', syllables: ['ZA', 'NA', 'HO', 'RIA'], emoji: '🥕' },
    { word: 'ZAPATOS', syllables: ['ZA', 'PA', 'TOS'], emoji: '👠' },
    { word: 'ZORROS', syllables: ['ZOR', 'ROS'], emoji: '🦊' },
    { word: 'ZAPATERO', syllables: ['ZA', 'PA', 'TE', 'RO'], emoji: '👞' },
    { word: 'ZAPALLO', syllables: ['ZA', 'PAL', 'LO'], emoji: '🎃' },
    { word: 'ZAGUÁN', syllables: ['ZA', 'GUÁN'], emoji: '🚪' },
    { word: 'ZOOLÓGICO', syllables: ['ZOO', 'LÓ', 'GI', 'CO'], emoji: '🦁' },
    { word: 'ZUMBIDO', syllables: ['ZUM', 'BI', 'DO'], emoji: '🐝' },
    { word: 'ZAFIRO', syllables: ['ZA', 'FI', 'RO'], emoji: '💎' },
    { word: 'ZAMBULLIDA', syllables: ['ZAM', 'BUL', 'LI', 'DA'], emoji: '🏊' },
    { word: 'ZOPILOTE', syllables: ['ZO', 'PI', 'LO', 'TE'], emoji: '🦅' },
    { word: 'ZURDO', syllables: ['ZUR', 'DO'], emoji: '✍️' },
    { word: 'ZARZAMORA', syllables: ['ZAR', 'ZA', 'MO', 'RA'], emoji: '🫐' },
    { word: 'ZAGAL', syllables: ['ZA', 'GAL'], emoji: '👦' },
    { word: 'ZÓCALO', syllables: ['ZÓ', 'CA', 'LO'], emoji: '🏛️' },
    { word: 'ZOQUETE', syllables: ['ZO', 'QUE', 'TE'], emoji: '🧦' },
    { word: 'ZARPA', syllables: ['ZAR', 'PA'], emoji: '🐾' },
    { word: 'ZEPPELIN', syllables: ['ZEP', 'PE', 'LIN'], emoji: '🎈' }
  ]
};
